version: '3'

services:
  slackbotlocal:
    image: slackbotlocal
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env  
    volumes:
      - "./data:/app/data"
      - "./.env:/app/.env"
    ports:
      - 8000:8000
  slackbotlocal-worker:
    image: slackbotlocal
    env_file: .env
    command: ["./worker_entrypoint.sh"]
    volumes:
      - "./data:/app/data"
      - "./.env:/app/.env"    
